import 'package:flutter/material.dart';
import 'package:finance_tracker/data/database.dart';
import 'package:finance_tracker/screens/dashboard.dart';
// NEW IMPORTS
import 'package:firebase_core/firebase_core.dart'; // Add this
import 'package:flutter_riverpod/flutter_riverpod.dart'; // Add this
import 'firebase_options.dart'; // Add this - This file will be generated by 'flutterfire configure'
import 'package:finance_tracker/views/splash_screen.dart'; // Add this import

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // NEW: Initialize Firebase before your local database
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Initialize database
  final db = FinanceDatabase();
  await db.loadData();

  // NEW: Wrap your app with ProviderScope
  runApp(ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Finance Tracker',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        useMaterial3: true,
      ),
      home: const SplashScreen(),
      debugShowCheckedModeBanner: false,
    );
  }
}
